### ISSUE TITLE
Evaluation fails with empty response on exactly the mainnet params on Hydra devnet

### ISSUE THREAD

**Issue by matiwinnetou** [bloxbean/aiken-jna-wrapper#5]
Exactly main-net params:

```
2023-03-23 09:46:59.094  INFO 33921 --- [    Test worker] c.b.c.aiken.tx.evaluator.TxEvaluator     : Transaction: 84a60081825820d2bf88d0c8e0e551855dd25e697a2b1db4654df21ea86d58fe31abf76f20cf9f18630182a300581d70c2d43417ca2475019ca9ae6a0b4393ef8275aefdd26acb792131187e011a0011d28a028201d8185841d8799fa1d8799f1a055381551a00429d13ffd8799f00001a00150205ff58200135df20dfaa2e729d776b13bd32fde3279c8a96b5b53124f553827e5b939f1d00ff82581d60f8a68cd18e59a6ace848155a0e967af64f4d00cf8acee8adc95a6b0d39b93102000d81825820d2bf88d0c8e0e551855dd25e697a2b1db4654df21ea86d58fe31abf76f20cf9f18641082581d60f8a68cd18e59a6ace848155a0e967af64f4d00cf8acee8adc95a6b0d1a34e3aceb111a000f4240a20581840000d8799f58200135df20dfaa2e729d776b13bd32fde3279c8a96b5b53124f553827e5b939f1dff820000068158fd58fb0100003232323232323232323232323232222533300a323232533300d3370e900000089919251375c6028002601600a264646464944dd6980b000980b0011bae3014001300b005300b0043011001300832533300b3370e9001180500088008a99806a4812a4578706563746564206f6e20696e636f727265637420636f6e7374727563746f722076617269616e742e001633006300800148008526163001001222533300d00214984cc024c004c038008ccc00c00cc03c008004cc0040052000222233330073370e00200601a4666600a00a66e000112002300f0010020022300737540024600a6ea80055cd2b9b5738aae7555cf2ab9f5742ae89f5f6
2023-03-23 09:46:59.094  INFO 33921 --- [    Test worker] c.b.c.aiken.tx.evaluator.TxEvaluator     : Inputs: 81825820d2bf88d0c8e0e551855dd25e697a2b1db4654df21ea86d58fe31abf76f20cf9f1863
2023-03-23 09:46:59.094  INFO 33921 --- [    Test worker] c.b.c.aiken.tx.evaluator.TxEvaluator     : Outputs: 81a300581d70c2d43417ca2475019ca9ae6a0b4393ef8275aefdd26acb792131187e011a00111958028201d8185836d8799f5820552fc855d6af5d239641b4d8fcf5023e5e376d1caae5f32ee65584e0b3be01841a001502051a055381551a00429d1300ff
2023-03-23 09:46:59.094  INFO 33921 --- [    Test worker] c.b.c.aiken.tx.evaluator.TxEvaluator     : CostMdlsHex : a10198af1a0003236119032c01011903e819023b00011903e8195e7104011903e818201a0001ca761928eb041959d818641959d818641959d818641959d818641959d818641959d81864186418641959d81864194c5118201a0002acfa182019b551041a000363151901ff00011a00015c3518201a000797751936f404021a0002ff941a0006ea7818dc0001011903e8196ff604021a0003bd081a00034ec5183e011a00102e0f19312a011a00032e801901a5011a0002da781903e819cf06011a00013a34182019a8f118201903e818201a00013aac0119e143041903e80a1a00030219189c011a00030219189c011a0003207c1901d9011a000330001901ff0119ccf3182019fd40182019ffd5182019581e18201940b318201a00012adf18201a0002ff941a0006ea7818dc0001011a00010f92192da7000119eabb18201a0002ff941a0006ea7818dc0001011a0002ff941a0006ea7818dc0001011a0011b22c1a0005fdde00021a000c504e197712041a001d6af61a0001425b041a00040c660004001a00014fab18201a0003236119032c010119a0de18201a00033d7618201979f41820197fb8182019a95d1820197df718201995aa18201a0223accc0a1a009063b91903fd0a1a02515e841980b30a
```

**Comment by matiwinnetou** [comment]
```
023-03-23 09:53:42.234  INFO 34323 --- [    Test worker] o.c.h.hydra.suppliers.HydraUtxoSupplier  : getUTxOResponse - last Seq:177

TxEvaluation Failed
com.bloxbean.cardano.aiken.tx.evaluator.exception.TxEvaluationException: TxEvaluation Failed
	at app//com.bloxbean.cardano.aiken.tx.evaluator.TxEvaluator.evaluateTx(TxEvaluator.java:113)
	at app//org.cardanofoundation.hydrapoc.commands.PlutusScriptUtil.evaluateExUnits(PlutusScriptUtil.java:96)
	at app//org.cardanofoundation.hydrapoc.batch.VoteBatcher.lambda$createAndPostBatchTransaction$6(VoteBatcher.java:160)
	at app//com.bloxbean.cardano.client.function.TxBuilder.lambda$andThen$0(TxBuilder.java:48)
	at app//com.bloxbean.cardano.client.function.TxBuilder.lambda$andThen$0(TxBuilder.java:47)
	at app//com.bloxbean.cardano.client.function.TxBuilderContext.build(TxBuilderContext.java:125)
	at app//com.bloxbean.cardano.client.function.TxBuilderContext.buildAndSign(TxBuilderContext.java:138)
	at app//org.cardanofoundation.hydrapoc.batch.VoteBatcher.createAndPostBatchTransaction(VoteBatcher.java:178)
	at app//org.cardanofoundation.hydrapoc.batch.VoteBatcher$$FastClassBySpringCGLIB$$1ed452d0.invoke(<generated>)
	```

**Comment by matiwinnetou** [comment]
Turns out this issue is caused by lack of ADA but error for a developer is very misleading. Can we improve on the error message that this is lack of funds case? @satran004 ?
